[package]
name = "jargon-args"
description = "A simple but smart command line parser"
readme = "README.md"
version = "0.2.4"
authors = ["Avery Murray <caverym@disroot.org>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/caverym/jargon"

[features]
no_mut = []
